server:
  port: 6711


logging:
  level:
    root: info
    com.spharos.conversion: debug


spharos:
  conversion:
    targets: MBERNO, MberNo, MBER-NO, mber-no, MBER_NO, mber_no, x-mber-no


spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    sql-script-encoding: utf-8
    initialization-mode: always
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true

  #  conversion project 에서 사용가능한 emoney-dev tns가 적용된 yaml information
  #  multi-datasource:
  #    readonly:
  #      jdbc-url: "bM3SwkPDoVrqW6d3OPUlHomKbnoC_XWvqGmvuXJeSMMElJuYEgQZxT3HIcuQJ_Qpq-GjKGFY61O6OghHHfhLXWlqpW-HLVnLHR6nzm-OmUY"
  #      username: "XLyTweQMUhsFZvCARqwx-w"
  #      password: 9Yw_qWJl0oxktLa9K_JlMA
  #      pool-name: hikari-cp
  #      maximum-pool-size: 50
  #      minimum-idle: 2
  #      data-source-properties:
  #        cachePrepStmts: true
  #        prepStmtCacheSize: 250
  #        prepStmtCacheSqlLimit: 2048
  #        useServerPrepStmts: true

  banner:
    location: classpath:/banner/spharos-banner.txt


osc:
  redis:
    holdingTime: '1'
    enabled: true
    host: mbrs-dev-emoney-redis.i4pbzq.clustercfg.apn2.cache.amazonaws.com
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2


other:
  redis:
    holdingTime: '1'
    enabled: true
    host: mbrs-dev-system-redis.i4pbzq.clustercfg.apn2.cache.amazonaws.com
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2


interface:
  url:
    sysm: http://localhost:9080
    api: http://localhost:9000
    svcm: http://localhost:9070
    solution: http://localhost:9090
    procedure: http://localhost:9092
